baseURL = "https://LalityaGhadiyaram.github.io/Portfolio/"
languageCode = "en-us"
title = "My Portfolio"
theme = "blowfish"
relativeURLs = true
canonifyURLs = true

[params]
defaultAppearance = "light"
colorScheme = "blue"

[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "Projects"
url = "/projects/"
weight = 2

[[menu.main]]
name = "About"
url = "/about/"
weight = 3
